language: bash

sudo: false

script:
  - bash -c 'shopt -s globstar; shellcheck --shell=ash -x **/*.sh'
  - bash -c '/usr/bin/file EnterRouterMode/bin/rsync'
  - bash -c 'file EnterRouterMode/bin/rsync'
  - bash -c 'find "EnterRouterMode/bin" -maxdepth 1 -type f | xargs -I % bash -c "/usr/bin/file % | grep \"ELF 32-bit LSB executable\" | grep MIPS"'
